### ISSUE TITLE
Component error: hwam_stove - Integration 'hwam_stove' not found.

### ISSUE THREAD

**Issue by tofrie** [mvn23/hwam_stove#3]
After the installation the following is displayed to me: "Component error: hwam_stove - Integration 'hwam_stove' not found." Homeassistant runs in Docker on a Synology NAS.

**Comment by mvn23** [comment]
Please make sure the repository is cloned in the correct location, i.e. you should have `__init__.py` in `custom_components/hwam_stove/__init__.py`.

**Comment by tofrie** [comment]
It‘s everything here:
<img width="693" alt="PNG-Bild" src="https://user-images.githubusercontent.com/60553702/106052099-8205d980-60e9-11eb-9ea7-abab8f691704.png">

**Comment by mvn23** [comment]
I'm not very familiar with docker and/or hassio, but the error seems to indicate that the files are not in the right place. The error message is not coming from the `hwam_stove` component, but from the component loader.
You may have more luck finding a solution in one of the hassio support channels.

**Comment by tofrie** [comment]
I tried Home Assistant Supervised and Home Assistant Operating System in Proxmox. Everytime the same… I got it work on a raspberry but I like to use my Intel nuc.

**Comment by mvn23** [comment]
If you're getting `Integration not found` errors, then this simply means what it says: the integration (code) can not be found. When running HA in docker (which is what happens with both installation methods you mentioned), `docker exec homeassistant ls /config/custom_components/hwam_stove/` on the host system should show you the integration files.
I can reproduce this error by adding `hwam_stove:` to `configuration.yaml` without having the `hwam_stove` folder in `custom_components`.
This is not a problem with the `hwam_stove` integration, but with your setup. Ask on the Home Assistant forum or discord server for help on setting up custom components when running Home Assistant in a docker container.

**Comment by Schrikt** [comment]
I got exact the same problem. Folder is in the right location. It started a couple of months ago after an home assistant update. I don't know exactly which version.

**Comment by mvn23** [comment]
I just realized that `manifest.json` is missing, which is required in "recent" versions of HA.

Please try the branch used in #4 and let me know if that works?

Note that I do not have access to a HWAM stove anymore, so no way for me to test this myself...

**Comment by Schrikt** [comment]
I have added the manifest.json and also 
This is my configuration.yaml code:
`hwam_stove:
  living_room:
    host: 192.168.xxx.xxx
    monitored_variables:
      - room_temperature
      - stove_temperature
      - oxygen_level
      - refill_alarm
      - night_lowering
      - operation_mode
      - phase
      - time_to_new_fire_wood
      - burn_level`

and this is in the custom_components folder:
![image](https://user-images.githubusercontent.com/60716169/130353562-b8de2fb1-2bda-45e0-b15e-2707b3555014.png)

**Comment by mvn23** [comment]
And does it work?

**Comment by Schrikt** [comment]
It does not work, but this is in the error log:

2021-08-22 14:08:27 ERROR (SyncWorker_21) [homeassistant.loader] The custom integration 'hwam_stove' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by Schrikt** [comment]
I have manually added "version": "1.0.0" and restarted the server. Now the integration is loaded again. Got a new error, I will post in a new issue.
