### ISSUE TITLE
How can i send the level through http?

### ISSUE THREAD

**Issue by tofrie** [mvn23/hwam_stove#7]
http://192.168.178.24/set_burn_level

**Comment by mvn23** [comment]
You have to POST some json to that address, e.g. `{"level":5}`
This does not look like an issue with `hwam_stove`. Please use other channels for questions like this in the future. All HTTP requests can be found in the `pystove` library.

**Comment by tofrie** [comment]
Maybe you can help?
https://forum.iobroker.net/topic/47697/wert-json-an-url-senden/77
